### ISSUE TITLE
Suggestion on getting around androidmanifest errors.

### ISSUE THREAD

**Issue by sirvon** [cine-io/cineio-broadcast-android#16]
Any suggestions from the team on getting around these android manifest errors:

```java
	is also present at io.cine:cineio-broadcast-android-sdk:0.0.13:39:9 value=(CineIOBroadcastActivity)
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:6:5 to override
	is also present at io.cine:cineio-broadcast-android-sdk:0.0.13:40:9 value=(@style/AppTheme)
	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:6:5 to override
/home/creator/AndroidStudioProjects/la/app/src/MYAPP/AndroidManifest.xml
Error:(14, 9) Attribute application@label value=(@string/app_name) from la.android-ago:android-ago:unspecified:14:9
Error:(54, 9) Attribute application@theme value=(@style/AppBaseTheme) from AndroidManifest.xml:54:9
Error:(6, 5) uses-sdk:minSdkVersion 16 cannot be smaller than version 18 declared in library /home/creator/AndroidStudioProjects/la/app/build/intermediates/exploded-aar/io.cine/cineio-broadcast-android-sdk/0.0.13/AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="io.cine.broadcast" to force usage
```

I've used the gradle provided suggestions to no avail

usually when I encounter these errors in libs, the amount of time spent trying to fix them amounts to half days....very costly. I've already encountered error after error with tools:replace.

most libs DONT have this problem
Is there anything you guys can do to the lib or guidance on tweaking the libs configure to make this go away gracefully?

would honestly be ashame not to put this lib to heavy usage as I intend!

**Comment by sirvon** [comment]
Error:(6, 5) tools:replace specified at line:6 for attribute tools:label, but no new value specified

after adding:

```java
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"

    package="com.loqooapps">

    <application
        tools:replace="label,theme"
```

don't know what to do now....

**Comment by growlsworth** [comment]
Hello @sirvon, 

The issue is that I have left overlapping labels in our sdk from the default ones Android Studio puts in an example app. I will remove them and publish a new version.

**Comment by sirvon** [comment]
it builds now ....
instead of using lib from maven
i cloned it and took out

```java
android:label="CineIOBroadcastActivity"
```
from androidmanifest.xml

it's not needed...

**Comment by sirvon** [comment]
thanks @growlsworth 
grabbing from maven/bintray is always best.

**Comment by sirvon** [comment]
android:theme aswell ....

**Comment by growlsworth** [comment]
https://github.com/cine-io/cineio-broadcast-android/releases/tag/v0.0.14

**Comment by growlsworth** [comment]
sometimes it takes a few hours for maven to be ready to download. But it's pushed.

**Comment by sirvon** [comment]
@growlsworth thank you for that quick fix. its all good now! :+1:
