### ISSUE TITLE
CineIOBroadcastActivity crashes on Galaxy S4 & S4 Mini.

### ISSUE THREAD

**Issue by cadesalaberry** [cine-io/cineio-broadcast-android#20]
Broadcasting a new stream does not seem to be working (At least on a S4 Mini).

Here is the [screencast](https://dl.dropboxusercontent.com/u/3394166/device-2015-05-01-162514.mp4).

You can check out the application logcat [here](http://pastebin.com/9CWC7KnX). From the look of it, the important part is line 99 (16:26:44.636) where it takes 30s to open the output file (some kind of timeout?).

Could it be a server side error ? What could I do to help you solve the problem ?

```
...
05-01 16:26:44.636    5530-5530/io.cine.example D/ffmpegbridge﹕ opening output url ...
05-01 16:26:44.636    5530-5530/io.cine.example I/ffmpegbridge﹕ Opening output file for writing at path rtmp://publish-sfo1.cine.io/live/X1bEyYg6?go59
05-01 16:27:16.050    5530-5530/io.cine.example E/ffmpegbridge﹕ ERROR: ffmpbr_prepare_stream error -- Unknown error occurred
05-01 16:27:16.050    5530-5530/io.cine.example D/ffmpegbridge﹕ logging (dumping) output_fmt_ctx log ...
...
```

_Edit: Also tested with a Galaxy S4, application logcat available [here](http://pastebin.com/ZE2mc0AM)._

**Comment by jeffreywescott** [comment]
There was a problem on our publish-sfo1 server -- it's fixed now. Closing.

**Comment by cadesalaberry** [comment]
Thanks @jeffreywescott !
